FROM ubuntu:18.04

ENV TZ=America/US
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update
RUN apt install -y \
        ninja-build \
        software-properties-common \
        python3-dev \
        python3-pip\
        wget
RUN  apt clean
RUN  wget  https://apt.llvm.org/llvm.sh
RUN file  llvm.sh
RUN chmod +x llvm.sh
RUN bash llvm.sh 10
RUN update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-10 100
RUN update-alternatives --install /usr/bin/cc cc /usr/bin/clang-10 100
RUN update-alternatives --config c++
RUN cc --version
RUN c++ --version
RUN rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./conanfile.txt ./conanfile.txt


RUN pip3 install pip --upgrade && \
    pip3 install --no-cache-dir scikit-build conan==1.60.0 pytest==6.2.5 cmake && \
    conan user && \
    conan profile new default --detect --force && \
    conan profile update settings.compiler.libcxx=libstdc++11 default && \
    conan config set general.parallel_download=$(nproc) && \
    conan config set general.cpu_count=$(nproc) && \
    conan profile update settings.compiler=clang default && \
    conan profile update settings.compiler.version=10 default && \
    conan profile update env.CXX=/usr/bin/clang++-10 default && \
    conan profile update env.CC=/usr/bin/clang-10 default && \
    conan install -if build . --build missing -s build_type=Release -s compiler.libcxx=libstdc++11

COPY ./header ./header
COPY ./source ./source
COPY ./test ./test
COPY ./benchmark ./benchmark
COPY ./examples ./examples
COPY ./cmake ./cmake
COPY ./CMakeLists.txt ./CMakeLists.txt
WORKDIR ./build


RUN cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -DALLOW_EXAMPLES=ON -DALLOW_TESTS=ON -DENABLE_TESTS_MEASUREMENTS=OFF -DALLOW_BENCHMARK=ON -DDEV_MODE=ON && \
    cmake --build .  --target all

RUN ctest -C Release --output-on-failure #--extra-verbose  #--rerun-failed -R message-id

