FROM ubuntu:22.04

ENV TZ=America/US
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update  \
    && apt upgrade -y \
    && apt install -y \
        ninja-build \
        software-properties-common \
        python3-dev \
        python3-pip\
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./conanfile.txt ./conanfile.txt

RUN pip3 install --no-cache-dir conan==1.60.0 pytest==6.2.5 cmake && \
    conan user && \
    conan profile new default --detect --force && \
    conan profile update settings.compiler.libcxx=libstdc++11 default && \
    conan config set general.parallel_download=$(nproc) && \
    conan config set general.cpu_count=$(nproc) && \
    conan install -if build . --build missing -s build_type=Release -s compiler.libcxx=libstdc++11

COPY ./header ./header
COPY ./source ./source
COPY ./test ./test
COPY ./benchmark ./benchmark
COPY ./examples ./examples
COPY ./cmake ./cmake
COPY ./CMakeLists.txt ./CMakeLists.txt
WORKDIR ./build


RUN cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=11 -DALLOW_EXAMPLES=ON -DALLOW_TESTS=ON -DENABLE_TESTS_MEASUREMENTS=OFF -DALLOW_BENCHMARK=ON -DDEV_MODE=ON && \
    cmake --build .  --target all

RUN ctest -C Release --output-on-failure #--extra-verbose  #--rerun-failed -R message-id

